# Generated by Django 4.2.2 on 2023-06-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('picture_of_Category', models.ImageField(default=None, upload_to='Category/photos/%Y/%m/%d')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Maqola turlari',
                'verbose_name_plural': 'Maqola turlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture_of_content', models.ImageField(default='Content\\photos\\default.png', upload_to='Content/photos/%Y/%m/%d/')),
                ('text_of_content', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('category_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.category')),
            ],
            options={
                'verbose_name': 'Har turdagi maqolalar',
                'verbose_name_plural': 'Har turdagi maqolalar',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
