# Generated by Django 4.2.2 on 2023-06-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
